### ISSUE TITLE
Site https://exercisync.com - not working Bad Gateway

### ISSUE THREAD

**Issue by filin2009** [Antash/exercisync#47]
When connecting to site https://exercisync.com
I have error
502 Bad Gateway
nginx/1.14.0 (Ubuntu)
Why so?

**Comment by Antash** [comment]
Sorry, but as long as aerobia.ru tracker retired it is pointless for me to continue maintaining exercisync.com. At least for free.

**Comment by filin2009** [comment]
Too bad. It was the only way for me to send activities from Strava to garmin connect.

**Comment by Antash** [comment]
@filin2009 unfortunately, after latest Strava-Garmin issues uploads to GC will be no longer supported from my side anyway. As well as tapiriik I should follow security policy to stay with Strava.
